### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PoulWalcker** [SQL-Academy/en.sql-academy#9]
"Print the beginning (start_pair field) and end **(and_pair field)** of the second and third sessions from the table Time pair." in Tasks for self-testing #2;

[Article Link](https://sql-academy.org/en/guide/limit)

<img width="942" alt="Screenshot 2024-10-15 at 9 17 38 PM" src="https://github.com/user-attachments/assets/ad805758-fd79-42f7-af6d-f0f61167ac71">

**Comment by PoulWalcker** [comment]
Typo # 2

[Article Link](https://sql-academy.org/en/guide/if-function#examples-with-the-ifnull-function)

Quote in the example is mismatched
<img width="768" alt="Screenshot 2024-10-18 at 6 07 42 PM" src="https://github.com/user-attachments/assets/6942f7fc-aa71-4e59-be7c-846525973ec2">

**Comment by NepeinAV** [comment]
Thanks!
